#include "stdafx.h"
#include "PlayerCreaturesImmunitySystem.h"

/// AUTOGENERATED METHODS ///

int PlayerCreaturesImmunitySystem::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int PlayerCreaturesImmunitySystem::Release() {
	return Simulator::cStrategy::Release();
}

const char* PlayerCreaturesImmunitySystem::GetName() const {
	return "Make_Player_Creatures_Immune::PlayersCreatureImmunitySystem";
}

bool PlayerCreaturesImmunitySystem::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool PlayerCreaturesImmunitySystem::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

bool PlayerCreaturesImmunitySystem::WriteToXML(Simulator::XmlSerializer* writexml)
{
	return false;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute PlayerCreaturesImmunitySystem::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void PlayerCreaturesImmunitySystem::Initialize() {
	App::ConsolePrintF("PlayersCreatureImmunitySystem initialized!, use 'makePlayerCreaturesImmune' in Creature Stage to make you creatures immune to the damage!.");

	sInstance = this;
	isSystemRunning = false;
}

void PlayerCreaturesImmunitySystem::Dispose() {

}

void PlayerCreaturesImmunitySystem::Update(int deltaTime, int deltaGameTime) {
	if (isSystemRunning == true) {
		if (Simulator::IsCreatureGame() == true) {
			ResourceKey avatarSpeciesKey = GameNounManager.GetAvatar()->mSpeciesKey;

			for (cCreatureAnimalPtr animal : Simulator::GetData<Simulator::cCreatureAnimal>()) {
				if (animal->mSpeciesKey == avatarSpeciesKey) {
					animal->SetHealthPoints(animal->GetMaxHitPoints());
				}
			}

		}
	}
}

PlayerCreaturesImmunitySystem* PlayerCreaturesImmunitySystem::Get()
{
	return sInstance;
}

void PlayerCreaturesImmunitySystem::ToggleSystemRun(bool RunningToggle)
{
	isSystemRunning = RunningToggle;
}

bool PlayerCreaturesImmunitySystem::GetSystemRun()
{
	return isSystemRunning;
}

PlayerCreaturesImmunitySystem* PlayerCreaturesImmunitySystem::sInstance;